//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSED04_HotelCecil.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int BillingID { get; set; }
        public int GuestIDFK { get; set; }
        public Nullable<int> RoomIDFK { get; set; }
        public decimal BarCharge { get; set; }
        public Nullable<decimal> WifiCharge { get; set; }
        public Nullable<decimal> TotalRoomCharge { get; set; }
        public Nullable<decimal> ExtraGuestCharge { get; set; }
        public Nullable<decimal> ExtraBedCharge { get; set; }
    
        public virtual RoomType RoomType { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
