//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSED04_HotelCecil.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public int GuestIDFK { get; set; }
        public int RoomIDFK { get; set; }
        public Nullable<int> NumGuests { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<bool> Wifi { get; set; }
        public Nullable<bool> MiniBar { get; set; }
        public Nullable<int> ExtraBed { get; set; }
        public Nullable<int> ExtraGuest { get; set; }
    
        public virtual RoomType RoomType { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
