//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSED04_HotelCecil.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomType()
        {
            this.Billings = new HashSet<Billing>();
            this.Bookings = new HashSet<Booking>();
        }
    
        public int RoomTypeID { get; set; }
        public string RoomTypeName { get; set; }
        public Nullable<int> SingleBed { get; set; }
        public Nullable<int> QueenBed { get; set; }
        public Nullable<decimal> RoomCharge { get; set; }
        public string RoomFeatures { get; set; }
        public Nullable<int> ExtraSingleBed { get; set; }
        public Nullable<int> ExtraQueenBed { get; set; }
        public Nullable<int> Sleeps { get; set; }
        public Nullable<int> ExtraGuest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billing> Billings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
